// <auto-generated />
using System;
using BusinessCore.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BusinessCore.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20190902170158_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.AddressMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine");

                    b.Property<string>("AddressLine2");

                    b.Property<string>("City");

                    b.Property<int>("CompanyId");

                    b.Property<long>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Latitude");

                    b.Property<string>("Locality");

                    b.Property<string>("Longitude");

                    b.Property<long?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<string>("Zip");

                    b.HasKey("Id");

                    b.ToTable("AddressMasters");
                });

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.LogInSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthToken");

                    b.Property<int>("CompanyId");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("DeviceId");

                    b.Property<DateTime>("ExpireOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<long>("UserMasterId");

                    b.HasKey("Id");

                    b.HasIndex("UserMasterId");

                    b.ToTable("LogInSessions");
                });

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.PriceMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId");

                    b.Property<long>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<float>("Discount");

                    b.Property<string>("DiscountText");

                    b.Property<bool>("IsActive");

                    b.Property<float>("MRP");

                    b.Property<float>("Price");

                    b.Property<string>("ProductId");

                    b.Property<long?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.ToTable("PriceMasters");
                });

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.ProductBarcode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<int>("CompanyId");

                    b.Property<long>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ProductMasterId");

                    b.Property<long?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("ProductMasterId");

                    b.ToTable("ProductBarcodes");
                });

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId");

                    b.Property<long>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<long?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 662, DateTimeKind.Local).AddTicks(731),
                            Description = "Soft drinks, coffees, teas, beers, and ales",
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 662, DateTimeKind.Local).AddTicks(1406),
                            Description = "Sweet and savory sauces, relishes, spreads, and seasonings",
                            Name = "Condiments"
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 662, DateTimeKind.Local).AddTicks(1415),
                            Description = "Dried fruit and bean curd",
                            Name = "Produce"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 662, DateTimeKind.Local).AddTicks(1419),
                            Description = "Prepared meats",
                            Name = "Meat/Poultry"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 662, DateTimeKind.Local).AddTicks(1421),
                            Description = "Seaweed and fish",
                            Name = "Seafood"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 662, DateTimeKind.Local).AddTicks(1427),
                            Description = "Cheeses",
                            Name = "Dairy Products"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 662, DateTimeKind.Local).AddTicks(1430),
                            Description = "Desserts, candies, and sweet breads",
                            Name = "Confections"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 662, DateTimeKind.Local).AddTicks(1432),
                            Description = "Breads, crackers, pasta, and cereal",
                            Name = "Grains/Cereals"
                        });
                });

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.ProductCategoryXref", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductCategoryId");

                    b.Property<string>("ProductMasterId");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("ProductMasterId");

                    b.ToTable("ProductCategoryXrefs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ProductCategoryId = 1,
                            ProductMasterId = "1"
                        },
                        new
                        {
                            Id = 2L,
                            ProductCategoryId = 1,
                            ProductMasterId = "2"
                        },
                        new
                        {
                            Id = 3L,
                            ProductCategoryId = 2,
                            ProductMasterId = "3"
                        },
                        new
                        {
                            Id = 4L,
                            ProductCategoryId = 2,
                            ProductMasterId = "4"
                        },
                        new
                        {
                            Id = 5L,
                            ProductCategoryId = 2,
                            ProductMasterId = "5"
                        },
                        new
                        {
                            Id = 6L,
                            ProductCategoryId = 2,
                            ProductMasterId = "6"
                        },
                        new
                        {
                            Id = 7L,
                            ProductCategoryId = 7,
                            ProductMasterId = "7"
                        },
                        new
                        {
                            Id = 8L,
                            ProductCategoryId = 2,
                            ProductMasterId = "8"
                        },
                        new
                        {
                            Id = 9L,
                            ProductCategoryId = 6,
                            ProductMasterId = "9"
                        },
                        new
                        {
                            Id = 10L,
                            ProductCategoryId = 8,
                            ProductMasterId = "10"
                        },
                        new
                        {
                            Id = 11L,
                            ProductCategoryId = 4,
                            ProductMasterId = "11"
                        },
                        new
                        {
                            Id = 12L,
                            ProductCategoryId = 4,
                            ProductMasterId = "12"
                        },
                        new
                        {
                            Id = 13L,
                            ProductCategoryId = 8,
                            ProductMasterId = "13"
                        },
                        new
                        {
                            Id = 14L,
                            ProductCategoryId = 7,
                            ProductMasterId = "14"
                        },
                        new
                        {
                            Id = 15L,
                            ProductCategoryId = 2,
                            ProductMasterId = "15"
                        },
                        new
                        {
                            Id = 16L,
                            ProductCategoryId = 3,
                            ProductMasterId = "16"
                        },
                        new
                        {
                            Id = 17L,
                            ProductCategoryId = 6,
                            ProductMasterId = "17"
                        },
                        new
                        {
                            Id = 18L,
                            ProductCategoryId = 8,
                            ProductMasterId = "18"
                        },
                        new
                        {
                            Id = 19L,
                            ProductCategoryId = 3,
                            ProductMasterId = "19"
                        },
                        new
                        {
                            Id = 20L,
                            ProductCategoryId = 3,
                            ProductMasterId = "20"
                        },
                        new
                        {
                            Id = 21L,
                            ProductCategoryId = 3,
                            ProductMasterId = "21"
                        },
                        new
                        {
                            Id = 22L,
                            ProductCategoryId = 5,
                            ProductMasterId = "22"
                        },
                        new
                        {
                            Id = 23L,
                            ProductCategoryId = 5,
                            ProductMasterId = "23"
                        },
                        new
                        {
                            Id = 24L,
                            ProductCategoryId = 1,
                            ProductMasterId = "24"
                        },
                        new
                        {
                            Id = 25L,
                            ProductCategoryId = 3,
                            ProductMasterId = "25"
                        },
                        new
                        {
                            Id = 26L,
                            ProductCategoryId = 3,
                            ProductMasterId = "26"
                        },
                        new
                        {
                            Id = 27L,
                            ProductCategoryId = 3,
                            ProductMasterId = "27"
                        },
                        new
                        {
                            Id = 28L,
                            ProductCategoryId = 7,
                            ProductMasterId = "28"
                        },
                        new
                        {
                            Id = 29L,
                            ProductCategoryId = 6,
                            ProductMasterId = "29"
                        },
                        new
                        {
                            Id = 30L,
                            ProductCategoryId = 8,
                            ProductMasterId = "30"
                        },
                        new
                        {
                            Id = 31L,
                            ProductCategoryId = 4,
                            ProductMasterId = "31"
                        },
                        new
                        {
                            Id = 32L,
                            ProductCategoryId = 4,
                            ProductMasterId = "32"
                        },
                        new
                        {
                            Id = 33L,
                            ProductCategoryId = 4,
                            ProductMasterId = "33"
                        },
                        new
                        {
                            Id = 34L,
                            ProductCategoryId = 1,
                            ProductMasterId = "34"
                        },
                        new
                        {
                            Id = 35L,
                            ProductCategoryId = 1,
                            ProductMasterId = "35"
                        },
                        new
                        {
                            Id = 36L,
                            ProductCategoryId = 8,
                            ProductMasterId = "36"
                        },
                        new
                        {
                            Id = 37L,
                            ProductCategoryId = 8,
                            ProductMasterId = "37"
                        },
                        new
                        {
                            Id = 38L,
                            ProductCategoryId = 1,
                            ProductMasterId = "38"
                        },
                        new
                        {
                            Id = 39L,
                            ProductCategoryId = 1,
                            ProductMasterId = "39"
                        },
                        new
                        {
                            Id = 40L,
                            ProductCategoryId = 8,
                            ProductMasterId = "40"
                        },
                        new
                        {
                            Id = 41L,
                            ProductCategoryId = 8,
                            ProductMasterId = "41"
                        },
                        new
                        {
                            Id = 42L,
                            ProductCategoryId = 5,
                            ProductMasterId = "42"
                        },
                        new
                        {
                            Id = 43L,
                            ProductCategoryId = 1,
                            ProductMasterId = "43"
                        },
                        new
                        {
                            Id = 44L,
                            ProductCategoryId = 2,
                            ProductMasterId = "44"
                        },
                        new
                        {
                            Id = 45L,
                            ProductCategoryId = 8,
                            ProductMasterId = "45"
                        },
                        new
                        {
                            Id = 46L,
                            ProductCategoryId = 8,
                            ProductMasterId = "46"
                        },
                        new
                        {
                            Id = 47L,
                            ProductCategoryId = 3,
                            ProductMasterId = "47"
                        },
                        new
                        {
                            Id = 48L,
                            ProductCategoryId = 3,
                            ProductMasterId = "48"
                        },
                        new
                        {
                            Id = 49L,
                            ProductCategoryId = 3,
                            ProductMasterId = "49"
                        },
                        new
                        {
                            Id = 50L,
                            ProductCategoryId = 3,
                            ProductMasterId = "50"
                        },
                        new
                        {
                            Id = 51L,
                            ProductCategoryId = 7,
                            ProductMasterId = "51"
                        },
                        new
                        {
                            Id = 52L,
                            ProductCategoryId = 5,
                            ProductMasterId = "52"
                        },
                        new
                        {
                            Id = 53L,
                            ProductCategoryId = 6,
                            ProductMasterId = "53"
                        },
                        new
                        {
                            Id = 54L,
                            ProductCategoryId = 6,
                            ProductMasterId = "54"
                        },
                        new
                        {
                            Id = 55L,
                            ProductCategoryId = 6,
                            ProductMasterId = "55"
                        },
                        new
                        {
                            Id = 56L,
                            ProductCategoryId = 5,
                            ProductMasterId = "56"
                        },
                        new
                        {
                            Id = 57L,
                            ProductCategoryId = 5,
                            ProductMasterId = "57"
                        },
                        new
                        {
                            Id = 58L,
                            ProductCategoryId = 8,
                            ProductMasterId = "58"
                        },
                        new
                        {
                            Id = 59L,
                            ProductCategoryId = 4,
                            ProductMasterId = "59"
                        },
                        new
                        {
                            Id = 60L,
                            ProductCategoryId = 4,
                            ProductMasterId = "60"
                        },
                        new
                        {
                            Id = 61L,
                            ProductCategoryId = 2,
                            ProductMasterId = "61"
                        },
                        new
                        {
                            Id = 62L,
                            ProductCategoryId = 3,
                            ProductMasterId = "62"
                        },
                        new
                        {
                            Id = 63L,
                            ProductCategoryId = 2,
                            ProductMasterId = "63"
                        },
                        new
                        {
                            Id = 64L,
                            ProductCategoryId = 5,
                            ProductMasterId = "64"
                        },
                        new
                        {
                            Id = 65L,
                            ProductCategoryId = 2,
                            ProductMasterId = "65"
                        },
                        new
                        {
                            Id = 66L,
                            ProductCategoryId = 2,
                            ProductMasterId = "66"
                        },
                        new
                        {
                            Id = 67L,
                            ProductCategoryId = 1,
                            ProductMasterId = "67"
                        },
                        new
                        {
                            Id = 68L,
                            ProductCategoryId = 3,
                            ProductMasterId = "68"
                        },
                        new
                        {
                            Id = 69L,
                            ProductCategoryId = 4,
                            ProductMasterId = "69"
                        },
                        new
                        {
                            Id = 70L,
                            ProductCategoryId = 1,
                            ProductMasterId = "70"
                        },
                        new
                        {
                            Id = 71L,
                            ProductCategoryId = 4,
                            ProductMasterId = "71"
                        },
                        new
                        {
                            Id = 72L,
                            ProductCategoryId = 4,
                            ProductMasterId = "72"
                        },
                        new
                        {
                            Id = 73L,
                            ProductCategoryId = 8,
                            ProductMasterId = "73"
                        },
                        new
                        {
                            Id = 74L,
                            ProductCategoryId = 7,
                            ProductMasterId = "74"
                        },
                        new
                        {
                            Id = 75L,
                            ProductCategoryId = 1,
                            ProductMasterId = "75"
                        },
                        new
                        {
                            Id = 76L,
                            ProductCategoryId = 1,
                            ProductMasterId = "76"
                        },
                        new
                        {
                            Id = 77L,
                            ProductCategoryId = 2,
                            ProductMasterId = "77"
                        });
                });

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.ProductMaster", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BannerImage");

                    b.Property<string>("Code");

                    b.Property<int>("CompanyId");

                    b.Property<long>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name");

                    b.Property<string>("ShortName");

                    b.Property<string>("ThumbImage");

                    b.Property<long?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.ToTable("ProductMasters");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            BannerImage = "1.jpg",
                            Code = "1",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 662, DateTimeKind.Local).AddTicks(9220),
                            Description = "",
                            IsActive = true,
                            Name = "Chai",
                            ShortName = "",
                            ThumbImage = "1.jpg"
                        },
                        new
                        {
                            Id = "2",
                            BannerImage = "2.jpg",
                            Code = "2",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3324),
                            Description = "",
                            IsActive = true,
                            Name = "Chang",
                            ShortName = "",
                            ThumbImage = "2.jpg"
                        },
                        new
                        {
                            Id = "3",
                            BannerImage = "3.jpg",
                            Code = "3",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3358),
                            Description = "",
                            IsActive = true,
                            Name = "Aniseed Syrup",
                            ShortName = "",
                            ThumbImage = "3.jpg"
                        },
                        new
                        {
                            Id = "4",
                            BannerImage = "4.jpg",
                            Code = "4",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3362),
                            Description = "",
                            IsActive = true,
                            Name = "Chef Anton's Cajun Seasoning",
                            ShortName = "",
                            ThumbImage = "4.jpg"
                        },
                        new
                        {
                            Id = "5",
                            BannerImage = "5.jpg",
                            Code = "5",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3365),
                            Description = "",
                            IsActive = true,
                            Name = "Chef Anton's Gumbo Mix",
                            ShortName = "",
                            ThumbImage = "5.jpg"
                        },
                        new
                        {
                            Id = "6",
                            BannerImage = "6.jpg",
                            Code = "6",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3372),
                            Description = "",
                            IsActive = true,
                            Name = "Grandma's Boysenberry Spread",
                            ShortName = "",
                            ThumbImage = "6.jpg"
                        },
                        new
                        {
                            Id = "7",
                            BannerImage = "7.jpg",
                            Code = "7",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3375),
                            Description = "",
                            IsActive = true,
                            Name = "Uncle Bob's Organic Dried Pears",
                            ShortName = "",
                            ThumbImage = "7.jpg"
                        },
                        new
                        {
                            Id = "8",
                            BannerImage = "8.jpg",
                            Code = "8",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3378),
                            Description = "",
                            IsActive = true,
                            Name = "Northwoods Cranberry Sauce",
                            ShortName = "",
                            ThumbImage = "8.jpg"
                        },
                        new
                        {
                            Id = "9",
                            BannerImage = "9.jpg",
                            Code = "9",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3381),
                            Description = "",
                            IsActive = true,
                            Name = "Mishi Kobe Niku",
                            ShortName = "",
                            ThumbImage = "9.jpg"
                        },
                        new
                        {
                            Id = "10",
                            BannerImage = "10.jpg",
                            Code = "10",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3386),
                            Description = "",
                            IsActive = true,
                            Name = "Ikura",
                            ShortName = "",
                            ThumbImage = "10.jpg"
                        },
                        new
                        {
                            Id = "11",
                            BannerImage = "11.jpg",
                            Code = "11",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3389),
                            Description = "",
                            IsActive = true,
                            Name = "Queso Cabrales",
                            ShortName = "",
                            ThumbImage = "11.jpg"
                        },
                        new
                        {
                            Id = "12",
                            BannerImage = "12.jpg",
                            Code = "12",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3392),
                            Description = "",
                            IsActive = true,
                            Name = "Queso Manchego La Pastora",
                            ShortName = "",
                            ThumbImage = "12.jpg"
                        },
                        new
                        {
                            Id = "13",
                            BannerImage = "13.jpg",
                            Code = "13",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3395),
                            Description = "",
                            IsActive = true,
                            Name = "Konbu",
                            ShortName = "",
                            ThumbImage = "13.jpg"
                        },
                        new
                        {
                            Id = "14",
                            BannerImage = "14.jpg",
                            Code = "14",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3398),
                            Description = "",
                            IsActive = true,
                            Name = "Tofu",
                            ShortName = "",
                            ThumbImage = "14.jpg"
                        },
                        new
                        {
                            Id = "15",
                            BannerImage = "15.jpg",
                            Code = "15",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3453),
                            Description = "",
                            IsActive = true,
                            Name = "Genen Shouyu",
                            ShortName = "",
                            ThumbImage = "15.jpg"
                        },
                        new
                        {
                            Id = "16",
                            BannerImage = "16.jpg",
                            Code = "16",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3456),
                            Description = "",
                            IsActive = true,
                            Name = "Pavlova",
                            ShortName = "",
                            ThumbImage = "16.jpg"
                        },
                        new
                        {
                            Id = "17",
                            BannerImage = "17.jpg",
                            Code = "17",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3460),
                            Description = "",
                            IsActive = true,
                            Name = "Alice Mutton",
                            ShortName = "",
                            ThumbImage = "17.jpg"
                        },
                        new
                        {
                            Id = "18",
                            BannerImage = "18.jpg",
                            Code = "18",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3465),
                            Description = "",
                            IsActive = true,
                            Name = "Carnarvon Tigers",
                            ShortName = "",
                            ThumbImage = "18.jpg"
                        },
                        new
                        {
                            Id = "19",
                            BannerImage = "19.jpg",
                            Code = "19",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3469),
                            Description = "",
                            IsActive = true,
                            Name = "Teatime Chocolate Biscuits",
                            ShortName = "",
                            ThumbImage = "19.jpg"
                        },
                        new
                        {
                            Id = "20",
                            BannerImage = "20.jpg",
                            Code = "20",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3472),
                            Description = "",
                            IsActive = true,
                            Name = "Sir Rodney's Marmalade",
                            ShortName = "",
                            ThumbImage = "20.jpg"
                        },
                        new
                        {
                            Id = "21",
                            BannerImage = "21.jpg",
                            Code = "21",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3475),
                            Description = "",
                            IsActive = true,
                            Name = "Sir Rodney's Scones",
                            ShortName = "",
                            ThumbImage = "21.jpg"
                        },
                        new
                        {
                            Id = "22",
                            BannerImage = "22.jpg",
                            Code = "22",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3478),
                            Description = "",
                            IsActive = true,
                            Name = "Gustaf's Knäckebröd",
                            ShortName = "",
                            ThumbImage = "22.jpg"
                        },
                        new
                        {
                            Id = "23",
                            BannerImage = "23.jpg",
                            Code = "23",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3481),
                            Description = "",
                            IsActive = true,
                            Name = "Tunnbröd",
                            ShortName = "",
                            ThumbImage = "23.jpg"
                        },
                        new
                        {
                            Id = "24",
                            BannerImage = "24.jpg",
                            Code = "24",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3484),
                            Description = "",
                            IsActive = true,
                            Name = "Guaraná Fantástica",
                            ShortName = "",
                            ThumbImage = "24.jpg"
                        },
                        new
                        {
                            Id = "25",
                            BannerImage = "25.jpg",
                            Code = "25",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3487),
                            Description = "",
                            IsActive = true,
                            Name = "NuNuCa Nuß-Nougat-Creme",
                            ShortName = "",
                            ThumbImage = "25.jpg"
                        },
                        new
                        {
                            Id = "26",
                            BannerImage = "26.jpg",
                            Code = "26",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3490),
                            Description = "",
                            IsActive = true,
                            Name = "Gumbär Gummibärchen",
                            ShortName = "",
                            ThumbImage = "26.jpg"
                        },
                        new
                        {
                            Id = "27",
                            BannerImage = "27.jpg",
                            Code = "27",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3493),
                            Description = "",
                            IsActive = true,
                            Name = "Schoggi Schokolade",
                            ShortName = "",
                            ThumbImage = "27.jpg"
                        },
                        new
                        {
                            Id = "28",
                            BannerImage = "28.jpg",
                            Code = "28",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3496),
                            Description = "",
                            IsActive = true,
                            Name = "Rössle Sauerkraut",
                            ShortName = "",
                            ThumbImage = "28.jpg"
                        },
                        new
                        {
                            Id = "29",
                            BannerImage = "29.jpg",
                            Code = "29",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3499),
                            Description = "",
                            IsActive = true,
                            Name = "Thüringer Rostbratwurst",
                            ShortName = "",
                            ThumbImage = "29.jpg"
                        },
                        new
                        {
                            Id = "30",
                            BannerImage = "30.jpg",
                            Code = "30",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3502),
                            Description = "",
                            IsActive = true,
                            Name = "Nord-Ost Matjeshering",
                            ShortName = "",
                            ThumbImage = "30.jpg"
                        },
                        new
                        {
                            Id = "31",
                            BannerImage = "31.jpg",
                            Code = "31",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3538),
                            Description = "",
                            IsActive = true,
                            Name = "Gorgonzola Telino",
                            ShortName = "",
                            ThumbImage = "31.jpg"
                        },
                        new
                        {
                            Id = "32",
                            BannerImage = "32.jpg",
                            Code = "32",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3541),
                            Description = "",
                            IsActive = true,
                            Name = "Mascarpone Fabioli",
                            ShortName = "",
                            ThumbImage = "32.jpg"
                        },
                        new
                        {
                            Id = "33",
                            BannerImage = "33.jpg",
                            Code = "33",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3544),
                            Description = "",
                            IsActive = true,
                            Name = "Geitost",
                            ShortName = "",
                            ThumbImage = "33.jpg"
                        },
                        new
                        {
                            Id = "34",
                            BannerImage = "34.jpg",
                            Code = "34",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3549),
                            Description = "",
                            IsActive = true,
                            Name = "Sasquatch Ale",
                            ShortName = "",
                            ThumbImage = "34.jpg"
                        },
                        new
                        {
                            Id = "35",
                            BannerImage = "35.jpg",
                            Code = "35",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3553),
                            Description = "",
                            IsActive = true,
                            Name = "Steeleye Stout",
                            ShortName = "",
                            ThumbImage = "35.jpg"
                        },
                        new
                        {
                            Id = "36",
                            BannerImage = "36.jpg",
                            Code = "36",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3556),
                            Description = "",
                            IsActive = true,
                            Name = "Inlagd Sill",
                            ShortName = "",
                            ThumbImage = "36.jpg"
                        },
                        new
                        {
                            Id = "37",
                            BannerImage = "37.jpg",
                            Code = "37",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3559),
                            Description = "",
                            IsActive = true,
                            Name = "Gravad lax",
                            ShortName = "",
                            ThumbImage = "37.jpg"
                        },
                        new
                        {
                            Id = "38",
                            BannerImage = "38.jpg",
                            Code = "38",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3563),
                            Description = "",
                            IsActive = true,
                            Name = "Côte de Blaye",
                            ShortName = "",
                            ThumbImage = "38.jpg"
                        },
                        new
                        {
                            Id = "39",
                            BannerImage = "39.jpg",
                            Code = "39",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3565),
                            Description = "",
                            IsActive = true,
                            Name = "Chartreuse verte",
                            ShortName = "",
                            ThumbImage = "39.jpg"
                        },
                        new
                        {
                            Id = "40",
                            BannerImage = "40.jpg",
                            Code = "40",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3568),
                            Description = "",
                            IsActive = true,
                            Name = "Boston Crab Meat",
                            ShortName = "",
                            ThumbImage = "40.jpg"
                        },
                        new
                        {
                            Id = "41",
                            BannerImage = "41.jpg",
                            Code = "41",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3571),
                            Description = "",
                            IsActive = true,
                            Name = "Jack's New England Clam Chowder",
                            ShortName = "",
                            ThumbImage = "41.jpg"
                        },
                        new
                        {
                            Id = "42",
                            BannerImage = "42.jpg",
                            Code = "42",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3574),
                            Description = "",
                            IsActive = true,
                            Name = "Singaporean Hokkien Fried Mee",
                            ShortName = "",
                            ThumbImage = "42.jpg"
                        },
                        new
                        {
                            Id = "43",
                            BannerImage = "43.jpg",
                            Code = "43",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3577),
                            Description = "",
                            IsActive = true,
                            Name = "Ipoh Coffee",
                            ShortName = "",
                            ThumbImage = "43.jpg"
                        },
                        new
                        {
                            Id = "44",
                            BannerImage = "44.jpg",
                            Code = "44",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3580),
                            Description = "",
                            IsActive = true,
                            Name = "Gula Malacca",
                            ShortName = "",
                            ThumbImage = "44.jpg"
                        },
                        new
                        {
                            Id = "45",
                            BannerImage = "45.jpg",
                            Code = "45",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3583),
                            Description = "",
                            IsActive = true,
                            Name = "Rogede sild",
                            ShortName = "",
                            ThumbImage = "45.jpg"
                        },
                        new
                        {
                            Id = "46",
                            BannerImage = "46.jpg",
                            Code = "46",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3619),
                            Description = "",
                            IsActive = true,
                            Name = "Spegesild",
                            ShortName = "",
                            ThumbImage = "46.jpg"
                        },
                        new
                        {
                            Id = "47",
                            BannerImage = "47.jpg",
                            Code = "47",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3623),
                            Description = "",
                            IsActive = true,
                            Name = "Zaanse koeken",
                            ShortName = "",
                            ThumbImage = "47.jpg"
                        },
                        new
                        {
                            Id = "48",
                            BannerImage = "48.jpg",
                            Code = "48",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3626),
                            Description = "",
                            IsActive = true,
                            Name = "Chocolade",
                            ShortName = "",
                            ThumbImage = "48.jpg"
                        },
                        new
                        {
                            Id = "49",
                            BannerImage = "49.jpg",
                            Code = "49",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3629),
                            Description = "",
                            IsActive = true,
                            Name = "Maxilaku",
                            ShortName = "",
                            ThumbImage = "49.jpg"
                        },
                        new
                        {
                            Id = "50",
                            BannerImage = "50.jpg",
                            Code = "50",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3632),
                            Description = "",
                            IsActive = true,
                            Name = "Valkoinen suklaa",
                            ShortName = "",
                            ThumbImage = "50.jpg"
                        },
                        new
                        {
                            Id = "51",
                            BannerImage = "51.jpg",
                            Code = "51",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3635),
                            Description = "",
                            IsActive = true,
                            Name = "Manjimup Dried Apples",
                            ShortName = "",
                            ThumbImage = "51.jpg"
                        },
                        new
                        {
                            Id = "52",
                            BannerImage = "52.jpg",
                            Code = "52",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3638),
                            Description = "",
                            IsActive = true,
                            Name = "Filo Mix",
                            ShortName = "",
                            ThumbImage = "52.jpg"
                        },
                        new
                        {
                            Id = "53",
                            BannerImage = "53.jpg",
                            Code = "53",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3641),
                            Description = "",
                            IsActive = true,
                            Name = "Perth Pasties",
                            ShortName = "",
                            ThumbImage = "53.jpg"
                        },
                        new
                        {
                            Id = "54",
                            BannerImage = "54.jpg",
                            Code = "54",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3643),
                            Description = "",
                            IsActive = true,
                            Name = "Tourtière",
                            ShortName = "",
                            ThumbImage = "54.jpg"
                        },
                        new
                        {
                            Id = "55",
                            BannerImage = "55.jpg",
                            Code = "55",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3646),
                            Description = "",
                            IsActive = true,
                            Name = "Pâté chinois",
                            ShortName = "",
                            ThumbImage = "55.jpg"
                        },
                        new
                        {
                            Id = "56",
                            BannerImage = "56.jpg",
                            Code = "56",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3649),
                            Description = "",
                            IsActive = true,
                            Name = "Gnocchi di nonna Alice",
                            ShortName = "",
                            ThumbImage = "56.jpg"
                        },
                        new
                        {
                            Id = "57",
                            BannerImage = "57.jpg",
                            Code = "57",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3652),
                            Description = "",
                            IsActive = true,
                            Name = "Ravioli Angelo",
                            ShortName = "",
                            ThumbImage = "57.jpg"
                        },
                        new
                        {
                            Id = "58",
                            BannerImage = "58.jpg",
                            Code = "58",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3655),
                            Description = "",
                            IsActive = true,
                            Name = "Escargots de Bourgogne",
                            ShortName = "",
                            ThumbImage = "58.jpg"
                        },
                        new
                        {
                            Id = "59",
                            BannerImage = "59.jpg",
                            Code = "59",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3658),
                            Description = "",
                            IsActive = true,
                            Name = "Raclette Courdavault",
                            ShortName = "",
                            ThumbImage = "59.jpg"
                        },
                        new
                        {
                            Id = "60",
                            BannerImage = "60.jpg",
                            Code = "60",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3661),
                            Description = "",
                            IsActive = true,
                            Name = "Camembert Pierrot",
                            ShortName = "",
                            ThumbImage = "60.jpg"
                        },
                        new
                        {
                            Id = "61",
                            BannerImage = "61.jpg",
                            Code = "61",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3663),
                            Description = "",
                            IsActive = true,
                            Name = "Sirop d'érable",
                            ShortName = "",
                            ThumbImage = "61.jpg"
                        },
                        new
                        {
                            Id = "62",
                            BannerImage = "62.jpg",
                            Code = "62",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3666),
                            Description = "",
                            IsActive = true,
                            Name = "Tarte au sucre",
                            ShortName = "",
                            ThumbImage = "62.jpg"
                        },
                        new
                        {
                            Id = "63",
                            BannerImage = "63.jpg",
                            Code = "63",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3702),
                            Description = "",
                            IsActive = true,
                            Name = "Vegie-spread",
                            ShortName = "",
                            ThumbImage = "63.jpg"
                        },
                        new
                        {
                            Id = "64",
                            BannerImage = "64.jpg",
                            Code = "64",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3705),
                            Description = "",
                            IsActive = true,
                            Name = "Wimmers gute Semmelknödel",
                            ShortName = "",
                            ThumbImage = "64.jpg"
                        },
                        new
                        {
                            Id = "65",
                            BannerImage = "65.jpg",
                            Code = "65",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3708),
                            Description = "",
                            IsActive = true,
                            Name = "Louisiana Fiery Hot Pepper Sauce",
                            ShortName = "",
                            ThumbImage = "65.jpg"
                        },
                        new
                        {
                            Id = "66",
                            BannerImage = "66.jpg",
                            Code = "66",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3713),
                            Description = "",
                            IsActive = true,
                            Name = "Louisiana Hot Spiced Okra",
                            ShortName = "",
                            ThumbImage = "66.jpg"
                        },
                        new
                        {
                            Id = "67",
                            BannerImage = "67.jpg",
                            Code = "67",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3716),
                            Description = "",
                            IsActive = true,
                            Name = "Laughing Lumberjack Lager",
                            ShortName = "",
                            ThumbImage = "67.jpg"
                        },
                        new
                        {
                            Id = "68",
                            BannerImage = "68.jpg",
                            Code = "68",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3719),
                            Description = "",
                            IsActive = true,
                            Name = "Scottish Longbreads",
                            ShortName = "",
                            ThumbImage = "68.jpg"
                        },
                        new
                        {
                            Id = "69",
                            BannerImage = "69.jpg",
                            Code = "69",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3722),
                            Description = "",
                            IsActive = true,
                            Name = "Gudbrandsdalsost",
                            ShortName = "",
                            ThumbImage = "69.jpg"
                        },
                        new
                        {
                            Id = "70",
                            BannerImage = "70.jpg",
                            Code = "70",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3724),
                            Description = "",
                            IsActive = true,
                            Name = "Outback Lager",
                            ShortName = "",
                            ThumbImage = "70.jpg"
                        },
                        new
                        {
                            Id = "71",
                            BannerImage = "71.jpg",
                            Code = "71",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3728),
                            Description = "",
                            IsActive = true,
                            Name = "Flotemysost",
                            ShortName = "",
                            ThumbImage = "71.jpg"
                        },
                        new
                        {
                            Id = "72",
                            BannerImage = "72.jpg",
                            Code = "72",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3731),
                            Description = "",
                            IsActive = true,
                            Name = "Mozzarella di Giovanni",
                            ShortName = "",
                            ThumbImage = "72.jpg"
                        },
                        new
                        {
                            Id = "73",
                            BannerImage = "73.jpg",
                            Code = "73",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3734),
                            Description = "",
                            IsActive = true,
                            Name = "Röd Kaviar",
                            ShortName = "",
                            ThumbImage = "73.jpg"
                        },
                        new
                        {
                            Id = "74",
                            BannerImage = "74.jpg",
                            Code = "74",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3737),
                            Description = "",
                            IsActive = true,
                            Name = "Longlife Tofu",
                            ShortName = "",
                            ThumbImage = "74.jpg"
                        },
                        new
                        {
                            Id = "75",
                            BannerImage = "75.jpg",
                            Code = "75",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3739),
                            Description = "",
                            IsActive = true,
                            Name = "Rhönbräu Klosterbier",
                            ShortName = "",
                            ThumbImage = "75.jpg"
                        },
                        new
                        {
                            Id = "76",
                            BannerImage = "76.jpg",
                            Code = "76",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3858),
                            Description = "",
                            IsActive = true,
                            Name = "Lakkalikööri",
                            ShortName = "",
                            ThumbImage = "76.jpg"
                        },
                        new
                        {
                            Id = "77",
                            BannerImage = "77.jpg",
                            Code = "77",
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 663, DateTimeKind.Local).AddTicks(3862),
                            Description = "",
                            IsActive = true,
                            Name = "Original Frankfurter grüne Soße",
                            ShortName = "",
                            ThumbImage = "77.jpg"
                        });
                });

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.RoleMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("RoleMasters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Description = "",
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 1,
                            Description = "",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.ShoppingCart", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CompanyId");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("Status");

                    b.Property<int>("StoreId");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.ShoppingCartItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ProductId");

                    b.Property<int>("Quantity");

                    b.Property<string>("ShoppingCartId");

                    b.Property<int>("SortOrder");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.StoreCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId");

                    b.Property<long>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<long?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.ToTable("StoreCategories");
                });

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.StoreCategoryXref", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("StoreCategoryId");

                    b.Property<int>("StoreMasterId");

                    b.HasKey("Id");

                    b.HasIndex("StoreCategoryId");

                    b.HasIndex("StoreMasterId");

                    b.ToTable("StoreCategoryXrefs");
                });

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.StoreMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressId");

                    b.Property<string>("BannerImage");

                    b.Property<string>("Code");

                    b.Property<int>("CompanyId");

                    b.Property<long>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name");

                    b.Property<string>("ShortName");

                    b.Property<long?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("StoreMasters");
                });

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.UserMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId");

                    b.Property<long>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailVerified");

                    b.Property<string>("FirstName");

                    b.Property<string>("FullName");

                    b.Property<string>("Gender");

                    b.Property<string>("ImageId");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.Property<string>("MobileNumber");

                    b.Property<bool>("MobileVerified");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Props");

                    b.Property<long?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.ToTable("UserMasters");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 613, DateTimeKind.Local).AddTicks(3258),
                            Email = "meetgirish.mjn@gmail.com",
                            EmailVerified = true,
                            FirstName = "Girish",
                            FullName = "Girish Mahajan",
                            Gender = "M",
                            ImageId = "",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = " Mahajan",
                            MobileNumber = "8871384762",
                            MobileVerified = true,
                            Name = "Admin",
                            Password = "0E37EZvfM10P1jAH1JRpV+OVlsT39xs451MD2WqKcsU=",
                            Props = ""
                        });
                });

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId");

                    b.Property<long>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<int>("RoleMasterId");

                    b.Property<long?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<long>("UserMasterId");

                    b.HasKey("Id");

                    b.HasIndex("RoleMasterId");

                    b.HasIndex("UserMasterId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedBy = 1L,
                            CreatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 615, DateTimeKind.Local).AddTicks(1672),
                            IsActive = true,
                            RoleMasterId = 1,
                            UpdatedBy = 1L,
                            UpdatedOn = new DateTime(2019, 9, 2, 22, 31, 57, 615, DateTimeKind.Local).AddTicks(136),
                            UserMasterId = 1L
                        });
                });

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.LogInSession", b =>
                {
                    b.HasOne("BusinessCore.DataAccess.DbModels.UserMaster", "UserMaster")
                        .WithMany()
                        .HasForeignKey("UserMasterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.ProductBarcode", b =>
                {
                    b.HasOne("BusinessCore.DataAccess.DbModels.ProductMaster")
                        .WithMany("BarCodes")
                        .HasForeignKey("ProductMasterId");
                });

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.ProductCategoryXref", b =>
                {
                    b.HasOne("BusinessCore.DataAccess.DbModels.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BusinessCore.DataAccess.DbModels.ProductMaster", "Product")
                        .WithMany()
                        .HasForeignKey("ProductMasterId");
                });

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.ShoppingCartItem", b =>
                {
                    b.HasOne("BusinessCore.DataAccess.DbModels.ShoppingCart", "ShoppingCart")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingCartId");
                });

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.StoreCategoryXref", b =>
                {
                    b.HasOne("BusinessCore.DataAccess.DbModels.StoreCategory", "Category")
                        .WithMany()
                        .HasForeignKey("StoreCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BusinessCore.DataAccess.DbModels.StoreMaster", "Store")
                        .WithMany()
                        .HasForeignKey("StoreMasterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.StoreMaster", b =>
                {
                    b.HasOne("BusinessCore.DataAccess.DbModels.AddressMaster", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");
                });

            modelBuilder.Entity("BusinessCore.DataAccess.DbModels.UserRole", b =>
                {
                    b.HasOne("BusinessCore.DataAccess.DbModels.RoleMaster", "RoleMaster")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleMasterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BusinessCore.DataAccess.DbModels.UserMaster", "UserMaster")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserMasterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
